backend:
  name: github
  repo: nvall13479/oep
  branch: main
  site_domain: nvall13479.github.io
  base_url: https://api.github.com
  auth_scope: repo
  use_graphql: false

media_folder: "img"
public_folder: "/oep/img"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Περιγραφή", name: "body", widget: "markdown" }
      - { label: "Εικόνα", name: "image", widget: "image" }
